export interface CityEntry {
  city: string
  dept: string
}

export const COLOMBIA_CITIES: CityEntry[] = [
  // Amazonas
  { city: 'Leticia', dept: 'Amazonas' },
  { city: 'Puerto Nariño', dept: 'Amazonas' },
  // Antioquia
  { city: 'Medellín', dept: 'Antioquia' },
  { city: 'Bello', dept: 'Antioquia' },
  { city: 'Itagüí', dept: 'Antioquia' },
  { city: 'Envigado', dept: 'Antioquia' },
  { city: 'Sabaneta', dept: 'Antioquia' },
  { city: 'Apartadó', dept: 'Antioquia' },
  { city: 'Turbo', dept: 'Antioquia' },
  { city: 'Rionegro', dept: 'Antioquia' },
  { city: 'Caucasia', dept: 'Antioquia' },
  { city: 'Copacabana', dept: 'Antioquia' },
  { city: 'Girardota', dept: 'Antioquia' },
  { city: 'La Ceja', dept: 'Antioquia' },
  { city: 'Marinilla', dept: 'Antioquia' },
  { city: 'El Carmen de Viboral', dept: 'Antioquia' },
  { city: 'Caldas', dept: 'Antioquia' },
  { city: 'Barbosa', dept: 'Antioquia' },
  { city: 'La Estrella', dept: 'Antioquia' },
  { city: 'El Retiro', dept: 'Antioquia' },
  { city: 'Guarne', dept: 'Antioquia' },
  { city: 'San Jerónimo', dept: 'Antioquia' },
  { city: 'Santa Fe de Antioquia', dept: 'Antioquia' },
  { city: 'Yarumal', dept: 'Antioquia' },
  { city: 'Puerto Berrío', dept: 'Antioquia' },
  { city: 'Chigorodó', dept: 'Antioquia' },
  { city: 'Carepa', dept: 'Antioquia' },
  // Arauca
  { city: 'Arauca', dept: 'Arauca' },
  { city: 'Saravena', dept: 'Arauca' },
  { city: 'Tame', dept: 'Arauca' },
  { city: 'Fortul', dept: 'Arauca' },
  { city: 'Arauquita', dept: 'Arauca' },
  // Atlántico
  { city: 'Barranquilla', dept: 'Atlántico' },
  { city: 'Soledad', dept: 'Atlántico' },
  { city: 'Malambo', dept: 'Atlántico' },
  { city: 'Sabanalarga', dept: 'Atlántico' },
  { city: 'Puerto Colombia', dept: 'Atlántico' },
  { city: 'Baranoa', dept: 'Atlántico' },
  { city: 'Galapa', dept: 'Atlántico' },
  { city: 'Juan de Acosta', dept: 'Atlántico' },
  // Bolívar
  { city: 'Cartagena', dept: 'Bolívar' },
  { city: 'Magangué', dept: 'Bolívar' },
  { city: 'Turbaco', dept: 'Bolívar' },
  { city: 'Arjona', dept: 'Bolívar' },
  { city: 'San Juan Nepomuceno', dept: 'Bolívar' },
  { city: 'El Carmen de Bolívar', dept: 'Bolívar' },
  // Boyacá
  { city: 'Tunja', dept: 'Boyacá' },
  { city: 'Duitama', dept: 'Boyacá' },
  { city: 'Sogamoso', dept: 'Boyacá' },
  { city: 'Chiquinquirá', dept: 'Boyacá' },
  { city: 'Paipa', dept: 'Boyacá' },
  { city: 'Villa de Leyva', dept: 'Boyacá' },
  { city: 'Moniquirá', dept: 'Boyacá' },
  { city: 'Garagoa', dept: 'Boyacá' },
  { city: 'Puerto Boyacá', dept: 'Boyacá' },
  // Caldas
  { city: 'Manizales', dept: 'Caldas' },
  { city: 'La Dorada', dept: 'Caldas' },
  { city: 'Chinchiná', dept: 'Caldas' },
  { city: 'Villamaría', dept: 'Caldas' },
  { city: 'Riosucio', dept: 'Caldas' },
  { city: 'Anserma', dept: 'Caldas' },
  // Caquetá
  { city: 'Florencia', dept: 'Caquetá' },
  { city: 'San Vicente del Caguán', dept: 'Caquetá' },
  { city: 'El Doncello', dept: 'Caquetá' },
  { city: 'Puerto Rico', dept: 'Caquetá' },
  // Casanare
  { city: 'Yopal', dept: 'Casanare' },
  { city: 'Aguazul', dept: 'Casanare' },
  { city: 'Villanueva', dept: 'Casanare' },
  { city: 'Tauramena', dept: 'Casanare' },
  { city: 'Paz de Ariporo', dept: 'Casanare' },
  // Cauca
  { city: 'Popayán', dept: 'Cauca' },
  { city: 'Santander de Quilichao', dept: 'Cauca' },
  { city: 'Puerto Tejada', dept: 'Cauca' },
  { city: 'El Bordo', dept: 'Cauca' },
  { city: 'Miranda', dept: 'Cauca' },
  { city: 'Corinto', dept: 'Cauca' },
  // Cesar
  { city: 'Valledupar', dept: 'Cesar' },
  { city: 'Aguachica', dept: 'Cesar' },
  { city: 'Bosconia', dept: 'Cesar' },
  { city: 'La Jagua de Ibirico', dept: 'Cesar' },
  { city: 'Codazzi', dept: 'Cesar' },
  { city: 'Curumaní', dept: 'Cesar' },
  // Chocó
  { city: 'Quibdó', dept: 'Chocó' },
  { city: 'Istmina', dept: 'Chocó' },
  { city: 'Condoto', dept: 'Chocó' },
  { city: 'Tadó', dept: 'Chocó' },
  // Córdoba
  { city: 'Montería', dept: 'Córdoba' },
  { city: 'Cereté', dept: 'Córdoba' },
  { city: 'Lorica', dept: 'Córdoba' },
  { city: 'Sahagún', dept: 'Córdoba' },
  { city: 'Montelíbano', dept: 'Córdoba' },
  { city: 'Tierralta', dept: 'Córdoba' },
  { city: 'Planeta Rica', dept: 'Córdoba' },
  // Cundinamarca + Bogotá
  { city: 'Bogotá D.C.', dept: 'Cundinamarca' },
  { city: 'Soacha', dept: 'Cundinamarca' },
  { city: 'Zipaquirá', dept: 'Cundinamarca' },
  { city: 'Fusagasugá', dept: 'Cundinamarca' },
  { city: 'Facatativá', dept: 'Cundinamarca' },
  { city: 'Girardot', dept: 'Cundinamarca' },
  { city: 'Chía', dept: 'Cundinamarca' },
  { city: 'Cajicá', dept: 'Cundinamarca' },
  { city: 'Mosquera', dept: 'Cundinamarca' },
  { city: 'Madrid', dept: 'Cundinamarca' },
  { city: 'Funza', dept: 'Cundinamarca' },
  { city: 'Cota', dept: 'Cundinamarca' },
  { city: 'La Calera', dept: 'Cundinamarca' },
  { city: 'Tabio', dept: 'Cundinamarca' },
  { city: 'Tenjo', dept: 'Cundinamarca' },
  { city: 'Sopó', dept: 'Cundinamarca' },
  { city: 'Tocancipá', dept: 'Cundinamarca' },
  { city: 'Gachancipá', dept: 'Cundinamarca' },
  { city: 'Sesquilé', dept: 'Cundinamarca' },
  { city: 'Villeta', dept: 'Cundinamarca' },
  { city: 'La Mesa', dept: 'Cundinamarca' },
  { city: 'Anapoima', dept: 'Cundinamarca' },
  { city: 'Ubaté', dept: 'Cundinamarca' },
  { city: 'Pacho', dept: 'Cundinamarca' },
  { city: 'Silvania', dept: 'Cundinamarca' },
  { city: 'Sibaté', dept: 'Cundinamarca' },
  { city: 'Nemocón', dept: 'Cundinamarca' },
  { city: 'Cogua', dept: 'Cundinamarca' },
  { city: 'El Rosal', dept: 'Cundinamarca' },
  { city: 'Subachoque', dept: 'Cundinamarca' },
  { city: 'Bojacá', dept: 'Cundinamarca' },
  { city: 'Ricaurte', dept: 'Cundinamarca' },
  { city: 'Flandes', dept: 'Cundinamarca' },
  // Guainía
  { city: 'Inírida', dept: 'Guainía' },
  // Guaviare
  { city: 'San José del Guaviare', dept: 'Guaviare' },
  // Huila
  { city: 'Neiva', dept: 'Huila' },
  { city: 'Pitalito', dept: 'Huila' },
  { city: 'Garzón', dept: 'Huila' },
  { city: 'La Plata', dept: 'Huila' },
  { city: 'Campoalegre', dept: 'Huila' },
  { city: 'San Agustín', dept: 'Huila' },
  // La Guajira
  { city: 'Riohacha', dept: 'La Guajira' },
  { city: 'Maicao', dept: 'La Guajira' },
  { city: 'Uribia', dept: 'La Guajira' },
  { city: 'Fonseca', dept: 'La Guajira' },
  { city: 'San Juan del Cesar', dept: 'La Guajira' },
  // Magdalena
  { city: 'Santa Marta', dept: 'Magdalena' },
  { city: 'Ciénaga', dept: 'Magdalena' },
  { city: 'Fundación', dept: 'Magdalena' },
  { city: 'El Banco', dept: 'Magdalena' },
  { city: 'Plato', dept: 'Magdalena' },
  // Meta
  { city: 'Villavicencio', dept: 'Meta' },
  { city: 'Acacías', dept: 'Meta' },
  { city: 'Granada', dept: 'Meta' },
  { city: 'San Martín', dept: 'Meta' },
  { city: 'Puerto López', dept: 'Meta' },
  { city: 'Restrepo', dept: 'Meta' },
  { city: 'Cumaral', dept: 'Meta' },
  // Nariño
  { city: 'Pasto', dept: 'Nariño' },
  { city: 'Tumaco', dept: 'Nariño' },
  { city: 'Ipiales', dept: 'Nariño' },
  { city: 'Túquerres', dept: 'Nariño' },
  { city: 'La Unión', dept: 'Nariño' },
  { city: 'Samaniego', dept: 'Nariño' },
  // Norte de Santander
  { city: 'Cúcuta', dept: 'Norte de Santander' },
  { city: 'Ocaña', dept: 'Norte de Santander' },
  { city: 'Pamplona', dept: 'Norte de Santander' },
  { city: 'Los Patios', dept: 'Norte de Santander' },
  { city: 'Villa del Rosario', dept: 'Norte de Santander' },
  { city: 'El Zulia', dept: 'Norte de Santander' },
  // Putumayo
  { city: 'Mocoa', dept: 'Putumayo' },
  { city: 'Puerto Asís', dept: 'Putumayo' },
  { city: 'Orito', dept: 'Putumayo' },
  { city: 'Valle del Guamuez', dept: 'Putumayo' },
  // Quindío
  { city: 'Armenia', dept: 'Quindío' },
  { city: 'Calarcá', dept: 'Quindío' },
  { city: 'Montenegro', dept: 'Quindío' },
  { city: 'Circasia', dept: 'Quindío' },
  { city: 'La Tebaida', dept: 'Quindío' },
  { city: 'Quimbaya', dept: 'Quindío' },
  { city: 'Salento', dept: 'Quindío' },
  // Risaralda
  { city: 'Pereira', dept: 'Risaralda' },
  { city: 'Dosquebradas', dept: 'Risaralda' },
  { city: 'Santa Rosa de Cabal', dept: 'Risaralda' },
  { city: 'La Virginia', dept: 'Risaralda' },
  // San Andrés y Providencia
  { city: 'San Andrés', dept: 'San Andrés y Providencia' },
  { city: 'Providencia', dept: 'San Andrés y Providencia' },
  // Santander
  { city: 'Bucaramanga', dept: 'Santander' },
  { city: 'Floridablanca', dept: 'Santander' },
  { city: 'Piedecuesta', dept: 'Santander' },
  { city: 'Girón', dept: 'Santander' },
  { city: 'Barrancabermeja', dept: 'Santander' },
  { city: 'San Gil', dept: 'Santander' },
  { city: 'Socorro', dept: 'Santander' },
  { city: 'Lebrija', dept: 'Santander' },
  // Sucre
  { city: 'Sincelejo', dept: 'Sucre' },
  { city: 'Corozal', dept: 'Sucre' },
  { city: 'San Marcos', dept: 'Sucre' },
  { city: 'Tolú', dept: 'Sucre' },
  { city: 'Sampués', dept: 'Sucre' },
  { city: 'San Onofre', dept: 'Sucre' },
  // Tolima
  { city: 'Ibagué', dept: 'Tolima' },
  { city: 'Espinal', dept: 'Tolima' },
  { city: 'Melgar', dept: 'Tolima' },
  { city: 'Honda', dept: 'Tolima' },
  { city: 'Mariquita', dept: 'Tolima' },
  { city: 'Chaparral', dept: 'Tolima' },
  { city: 'Líbano', dept: 'Tolima' },
  { city: 'Flandes', dept: 'Tolima' },
  // Valle del Cauca
  { city: 'Cali', dept: 'Valle del Cauca' },
  { city: 'Palmira', dept: 'Valle del Cauca' },
  { city: 'Buenaventura', dept: 'Valle del Cauca' },
  { city: 'Tuluá', dept: 'Valle del Cauca' },
  { city: 'Buga', dept: 'Valle del Cauca' },
  { city: 'Cartago', dept: 'Valle del Cauca' },
  { city: 'Yumbo', dept: 'Valle del Cauca' },
  { city: 'Jamundí', dept: 'Valle del Cauca' },
  { city: 'Candelaria', dept: 'Valle del Cauca' },
  { city: 'Dagua', dept: 'Valle del Cauca' },
  { city: 'Florida', dept: 'Valle del Cauca' },
  { city: 'Pradera', dept: 'Valle del Cauca' },
  { city: 'Sevilla', dept: 'Valle del Cauca' },
  { city: 'Caicedonia', dept: 'Valle del Cauca' },
  // Vaupés
  { city: 'Mitú', dept: 'Vaupés' },
  // Vichada
  { city: 'Puerto Carreño', dept: 'Vichada' },
]
