export interface BarrioEntry {
  barrio: string
  comuna: string
}

export const MEDELLIN_BARRIOS: BarrioEntry[] = [
  // Comuna 1 - Popular
  { barrio: 'Santo Domingo Savio Nº 1', comuna: '1 - Popular' },
  { barrio: 'Santo Domingo Savio Nº 2', comuna: '1 - Popular' },
  { barrio: 'Popular', comuna: '1 - Popular' },
  { barrio: 'Granizal', comuna: '1 - Popular' },
  { barrio: 'Moscú Nº 2', comuna: '1 - Popular' },
  { barrio: 'Villa Guadalupe', comuna: '1 - Popular' },
  { barrio: 'San Pablo', comuna: '1 - Popular' },
  { barrio: 'Aldea Pablo VI', comuna: '1 - Popular' },
  { barrio: 'La Esperanza Nº 2', comuna: '1 - Popular' },
  { barrio: 'El Compromiso', comuna: '1 - Popular' },
  { barrio: 'La Avanzada', comuna: '1 - Popular' },
  { barrio: 'Carpinelo', comuna: '1 - Popular' },
  // Comuna 2 - Santa Cruz
  { barrio: 'La Isla', comuna: '2 - Santa Cruz' },
  { barrio: 'El Playón de Los Comuneros', comuna: '2 - Santa Cruz' },
  { barrio: 'Pablo VI', comuna: '2 - Santa Cruz' },
  { barrio: 'La Frontera', comuna: '2 - Santa Cruz' },
  { barrio: 'La Francia', comuna: '2 - Santa Cruz' },
  { barrio: 'Andalucía', comuna: '2 - Santa Cruz' },
  { barrio: 'Villa del Socorro', comuna: '2 - Santa Cruz' },
  { barrio: 'Villa Niza', comuna: '2 - Santa Cruz' },
  { barrio: 'Moscú Nº 1', comuna: '2 - Santa Cruz' },
  { barrio: 'Santa Cruz', comuna: '2 - Santa Cruz' },
  { barrio: 'La Rosa', comuna: '2 - Santa Cruz' },
  // Comuna 3 - Manrique
  { barrio: 'La Salle', comuna: '3 - Manrique' },
  { barrio: 'Las Granjas', comuna: '3 - Manrique' },
  { barrio: 'Campo Valdés Nº 2', comuna: '3 - Manrique' },
  { barrio: 'Santa Inés', comuna: '3 - Manrique' },
  { barrio: 'El Raizal', comuna: '3 - Manrique' },
  { barrio: 'El Pomar', comuna: '3 - Manrique' },
  { barrio: 'Manrique Central Nº 2', comuna: '3 - Manrique' },
  { barrio: 'Manrique Oriental', comuna: '3 - Manrique' },
  { barrio: 'Versalles Nº 1', comuna: '3 - Manrique' },
  { barrio: 'Versalles Nº 2', comuna: '3 - Manrique' },
  { barrio: 'La Cruz', comuna: '3 - Manrique' },
  { barrio: 'Oriente', comuna: '3 - Manrique' },
  { barrio: 'María Cano – Carambolas', comuna: '3 - Manrique' },
  { barrio: 'San José La Cima Nº 1', comuna: '3 - Manrique' },
  { barrio: 'San José La Cima Nº 2', comuna: '3 - Manrique' },
  // Comuna 4 - Aranjuez
  { barrio: 'Berlín', comuna: '4 - Aranjuez' },
  { barrio: 'San Isidro', comuna: '4 - Aranjuez' },
  { barrio: 'Palermo', comuna: '4 - Aranjuez' },
  { barrio: 'Bermejal – Los Álamos', comuna: '4 - Aranjuez' },
  { barrio: 'Moravia', comuna: '4 - Aranjuez' },
  { barrio: 'Sevilla', comuna: '4 - Aranjuez' },
  { barrio: 'San Pedro', comuna: '4 - Aranjuez' },
  { barrio: 'Manrique Central Nº 1', comuna: '4 - Aranjuez' },
  { barrio: 'Campo Valdés Nº 1', comuna: '4 - Aranjuez' },
  { barrio: 'Las Esmeraldas', comuna: '4 - Aranjuez' },
  { barrio: 'La Piñuela', comuna: '4 - Aranjuez' },
  { barrio: 'Aranjuez', comuna: '4 - Aranjuez' },
  { barrio: 'Brasilia', comuna: '4 - Aranjuez' },
  { barrio: 'Miranda', comuna: '4 - Aranjuez' },
  // Comuna 5 - Castilla
  { barrio: 'Toscana', comuna: '5 - Castilla' },
  { barrio: 'Las Brisas', comuna: '5 - Castilla' },
  { barrio: 'Florencia', comuna: '5 - Castilla' },
  { barrio: 'Tejelo', comuna: '5 - Castilla' },
  { barrio: 'Boyacá', comuna: '5 - Castilla' },
  { barrio: 'Héctor Abad Gómez', comuna: '5 - Castilla' },
  { barrio: 'Belalcázar', comuna: '5 - Castilla' },
  { barrio: 'Girardot', comuna: '5 - Castilla' },
  { barrio: 'Tricentenario', comuna: '5 - Castilla' },
  { barrio: 'Castilla', comuna: '5 - Castilla' },
  { barrio: 'Francisco Antonio Zea', comuna: '5 - Castilla' },
  { barrio: 'Alfonso López', comuna: '5 - Castilla' },
  { barrio: 'Caribe', comuna: '5 - Castilla' },
  { barrio: 'El Progreso', comuna: '5 - Castilla' },
  // Comuna 6 - Doce de Octubre
  { barrio: 'Santander', comuna: '6 - Doce de Octubre' },
  { barrio: 'Doce de Octubre Nº 1', comuna: '6 - Doce de Octubre' },
  { barrio: 'Doce de Octubre Nº 2', comuna: '6 - Doce de Octubre' },
  { barrio: 'Pedregal', comuna: '6 - Doce de Octubre' },
  { barrio: 'La Esperanza', comuna: '6 - Doce de Octubre' },
  { barrio: 'San Martín de Porres', comuna: '6 - Doce de Octubre' },
  { barrio: 'Kennedy', comuna: '6 - Doce de Octubre' },
  { barrio: 'Picacho', comuna: '6 - Doce de Octubre' },
  { barrio: 'Picachito', comuna: '6 - Doce de Octubre' },
  { barrio: 'Mirador del Doce', comuna: '6 - Doce de Octubre' },
  { barrio: 'Progreso Nº 2', comuna: '6 - Doce de Octubre' },
  { barrio: 'El Triunfo', comuna: '6 - Doce de Octubre' },
  // Comuna 7 - Robledo
  { barrio: 'Cerro El Volador', comuna: '7 - Robledo' },
  { barrio: 'San Germán', comuna: '7 - Robledo' },
  { barrio: 'Facultad de Minas', comuna: '7 - Robledo' },
  { barrio: 'La Pilarica', comuna: '7 - Robledo' },
  { barrio: 'Bosques de San Pablo', comuna: '7 - Robledo' },
  { barrio: 'Altamira', comuna: '7 - Robledo' },
  { barrio: 'Córdoba', comuna: '7 - Robledo' },
  { barrio: 'López de Mesa', comuna: '7 - Robledo' },
  { barrio: 'El Diamante', comuna: '7 - Robledo' },
  { barrio: 'Aures Nº 1', comuna: '7 - Robledo' },
  { barrio: 'Aures Nº 2', comuna: '7 - Robledo' },
  { barrio: 'Bello Horizonte', comuna: '7 - Robledo' },
  { barrio: 'Villa Flora', comuna: '7 - Robledo' },
  { barrio: 'Palenque', comuna: '7 - Robledo' },
  { barrio: 'Robledo', comuna: '7 - Robledo' },
  { barrio: 'Cucaracho', comuna: '7 - Robledo' },
  { barrio: 'Fuente Clara', comuna: '7 - Robledo' },
  { barrio: 'Santa Margarita', comuna: '7 - Robledo' },
  { barrio: 'Olaya Herrera', comuna: '7 - Robledo' },
  { barrio: 'Pajarito', comuna: '7 - Robledo' },
  { barrio: 'Monteclaro', comuna: '7 - Robledo' },
  { barrio: 'Nueva Villa de La Iguaná', comuna: '7 - Robledo' },
  // Comuna 8 - Villa Hermosa
  { barrio: 'Villa Hermosa', comuna: '8 - Villa Hermosa' },
  { barrio: 'La Mansión', comuna: '8 - Villa Hermosa' },
  { barrio: 'San Miguel', comuna: '8 - Villa Hermosa' },
  { barrio: 'La Ladera', comuna: '8 - Villa Hermosa' },
  { barrio: 'Batallón Girardot', comuna: '8 - Villa Hermosa' },
  { barrio: 'Llanaditas', comuna: '8 - Villa Hermosa' },
  { barrio: 'Los Mangos', comuna: '8 - Villa Hermosa' },
  { barrio: 'Enciso', comuna: '8 - Villa Hermosa' },
  { barrio: 'Sucre', comuna: '8 - Villa Hermosa' },
  { barrio: 'El Pinal', comuna: '8 - Villa Hermosa' },
  { barrio: 'Trece de Noviembre', comuna: '8 - Villa Hermosa' },
  { barrio: 'La Libertad', comuna: '8 - Villa Hermosa' },
  { barrio: 'Villatina', comuna: '8 - Villa Hermosa' },
  { barrio: 'San Antonio', comuna: '8 - Villa Hermosa' },
  { barrio: 'Las Estancias', comuna: '8 - Villa Hermosa' },
  { barrio: 'Villa Turbay', comuna: '8 - Villa Hermosa' },
  { barrio: 'La Sierra', comuna: '8 - Villa Hermosa' },
  { barrio: 'Villa Lilliam', comuna: '8 - Villa Hermosa' },
  // Comuna 9 - Buenos Aires
  { barrio: 'Juan Pablo II', comuna: '9 - Buenos Aires' },
  { barrio: 'Barrios de Jesús', comuna: '9 - Buenos Aires' },
  { barrio: 'Bomboná Nº 2', comuna: '9 - Buenos Aires' },
  { barrio: 'Los Cerros El Vergel', comuna: '9 - Buenos Aires' },
  { barrio: 'Alejandro Echavarría', comuna: '9 - Buenos Aires' },
  { barrio: 'Barrio Caicedo', comuna: '9 - Buenos Aires' },
  { barrio: 'Buenos Aires', comuna: '9 - Buenos Aires' },
  { barrio: 'Miraflores', comuna: '9 - Buenos Aires' },
  { barrio: 'Cataluña', comuna: '9 - Buenos Aires' },
  { barrio: 'La Milagrosa', comuna: '9 - Buenos Aires' },
  { barrio: 'Gerona', comuna: '9 - Buenos Aires' },
  { barrio: 'El Salvador', comuna: '9 - Buenos Aires' },
  { barrio: 'Loreto', comuna: '9 - Buenos Aires' },
  { barrio: 'Asomadera Nº 1', comuna: '9 - Buenos Aires' },
  { barrio: 'Asomadera Nº 2', comuna: '9 - Buenos Aires' },
  { barrio: 'Asomadera Nº 3', comuna: '9 - Buenos Aires' },
  { barrio: 'Ocho de Marzo', comuna: '9 - Buenos Aires' },
  // Comuna 10 - La Candelaria
  { barrio: 'Prado', comuna: '10 - La Candelaria' },
  { barrio: 'Jesús Nazareno', comuna: '10 - La Candelaria' },
  { barrio: 'El Chagualo', comuna: '10 - La Candelaria' },
  { barrio: 'Estación Villa', comuna: '10 - La Candelaria' },
  { barrio: 'San Benito', comuna: '10 - La Candelaria' },
  { barrio: 'Guayaquil', comuna: '10 - La Candelaria' },
  { barrio: 'Corazón de Jesús', comuna: '10 - La Candelaria' },
  { barrio: 'Calle Nueva', comuna: '10 - La Candelaria' },
  { barrio: 'Perpetuo Socorro', comuna: '10 - La Candelaria' },
  { barrio: 'Barrio Colón', comuna: '10 - La Candelaria' },
  { barrio: 'Las Palmas', comuna: '10 - La Candelaria' },
  { barrio: 'Bomboná Nº 1', comuna: '10 - La Candelaria' },
  { barrio: 'Boston', comuna: '10 - La Candelaria' },
  { barrio: 'Los Ángeles', comuna: '10 - La Candelaria' },
  { barrio: 'Villa Nueva', comuna: '10 - La Candelaria' },
  { barrio: 'La Candelaria', comuna: '10 - La Candelaria' },
  { barrio: 'San Diego', comuna: '10 - La Candelaria' },
  // Comuna 11 - Laureles – Estadio
  { barrio: 'Carlos E. Restrepo', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Suramericana', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Naranjal', comuna: '11 - Laureles – Estadio' },
  { barrio: 'San Joaquín', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Los Conquistadores', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Bolivariana', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Laureles', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Las Acacias', comuna: '11 - Laureles – Estadio' },
  { barrio: 'La Castellana', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Lorena', comuna: '11 - Laureles – Estadio' },
  { barrio: 'El Velódromo', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Estadio', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Los Colores', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Cuarta Brigada', comuna: '11 - Laureles – Estadio' },
  { barrio: 'Florida Nueva', comuna: '11 - Laureles – Estadio' },
  // Comuna 12 - La América
  { barrio: 'Ferrini', comuna: '12 - La América' },
  { barrio: 'Calasanz', comuna: '12 - La América' },
  { barrio: 'Los Pinos', comuna: '12 - La América' },
  { barrio: 'La América', comuna: '12 - La América' },
  { barrio: 'La Floresta', comuna: '12 - La América' },
  { barrio: 'Santa Lucía', comuna: '12 - La América' },
  { barrio: 'El Danubio', comuna: '12 - La América' },
  { barrio: 'Campo Alegre', comuna: '12 - La América' },
  { barrio: 'Santa Mónica', comuna: '12 - La América' },
  { barrio: 'Barrio Cristóbal', comuna: '12 - La América' },
  { barrio: 'Simón Bolívar', comuna: '12 - La América' },
  { barrio: 'Santa Teresita', comuna: '12 - La América' },
  { barrio: 'Calasanz Parte Alta', comuna: '12 - La América' },
  // Comuna 13 - San Javier
  { barrio: 'El Pesebre', comuna: '13 - San Javier' },
  { barrio: 'Blanquizal', comuna: '13 - San Javier' },
  { barrio: 'Santa Rosa de Lima', comuna: '13 - San Javier' },
  { barrio: 'Los Alcázares', comuna: '13 - San Javier' },
  { barrio: 'Metropolitano', comuna: '13 - San Javier' },
  { barrio: 'La Pradera', comuna: '13 - San Javier' },
  { barrio: 'Juan XXIII – La Quiebra', comuna: '13 - San Javier' },
  { barrio: 'San Javier Nº 2', comuna: '13 - San Javier' },
  { barrio: 'San Javier Nº 1', comuna: '13 - San Javier' },
  { barrio: 'Veinte de Julio', comuna: '13 - San Javier' },
  { barrio: 'Belencito', comuna: '13 - San Javier' },
  { barrio: 'Betania', comuna: '13 - San Javier' },
  { barrio: 'El Corazón', comuna: '13 - San Javier' },
  { barrio: 'Las Independencias', comuna: '13 - San Javier' },
  { barrio: 'Nuevos Conquistadores', comuna: '13 - San Javier' },
  { barrio: 'El Salado', comuna: '13 - San Javier' },
  { barrio: 'Eduardo Santos', comuna: '13 - San Javier' },
  { barrio: 'Antonio Nariño', comuna: '13 - San Javier' },
  { barrio: 'El Socorro', comuna: '13 - San Javier' },
  // Comuna 14 - El Poblado
  { barrio: 'Barrio Colombia', comuna: '14 - El Poblado' },
  { barrio: 'Simesa', comuna: '14 - El Poblado' },
  { barrio: 'Villa Carlota', comuna: '14 - El Poblado' },
  { barrio: 'Castropol', comuna: '14 - El Poblado' },
  { barrio: 'Lalinde', comuna: '14 - El Poblado' },
  { barrio: 'Las Lomas Nº 1', comuna: '14 - El Poblado' },
  { barrio: 'Las Lomas Nº 2', comuna: '14 - El Poblado' },
  { barrio: 'Altos del Poblado', comuna: '14 - El Poblado' },
  { barrio: 'El Tesoro', comuna: '14 - El Poblado' },
  { barrio: 'Los Naranjos', comuna: '14 - El Poblado' },
  { barrio: 'Los Balsos Nº 1', comuna: '14 - El Poblado' },
  { barrio: 'San Lucas', comuna: '14 - El Poblado' },
  { barrio: 'El Diamante Nº 2', comuna: '14 - El Poblado' },
  { barrio: 'El Castillo', comuna: '14 - El Poblado' },
  { barrio: 'Los Balsos Nº 2', comuna: '14 - El Poblado' },
  { barrio: 'Alejandría', comuna: '14 - El Poblado' },
  { barrio: 'La Florida', comuna: '14 - El Poblado' },
  { barrio: 'El Poblado', comuna: '14 - El Poblado' },
  { barrio: 'Manila', comuna: '14 - El Poblado' },
  { barrio: 'Astorga', comuna: '14 - El Poblado' },
  { barrio: 'Patio Bonito', comuna: '14 - El Poblado' },
  { barrio: 'La Aguacatala', comuna: '14 - El Poblado' },
  { barrio: 'Santa María de Los Ángeles', comuna: '14 - El Poblado' },
  // Comuna 15 - Guayabal
  { barrio: 'Tenche', comuna: '15 - Guayabal' },
  { barrio: 'Trinidad', comuna: '15 - Guayabal' },
  { barrio: 'Santa Fe', comuna: '15 - Guayabal' },
  { barrio: 'Parque Juan Pablo II', comuna: '15 - Guayabal' },
  { barrio: 'Campo Amor', comuna: '15 - Guayabal' },
  { barrio: 'Noel', comuna: '15 - Guayabal' },
  { barrio: 'Cristo Rey', comuna: '15 - Guayabal' },
  { barrio: 'Guayabal', comuna: '15 - Guayabal' },
  { barrio: 'La Colina', comuna: '15 - Guayabal' },
  { barrio: 'El Rodeo', comuna: '15 - Guayabal' },
  // Comuna 16 - Belén
  { barrio: 'Fátima', comuna: '16 - Belén' },
  { barrio: 'Rosales', comuna: '16 - Belén' },
  { barrio: 'Belén', comuna: '16 - Belén' },
  { barrio: 'Granada', comuna: '16 - Belén' },
  { barrio: 'San Bernardo', comuna: '16 - Belén' },
  { barrio: 'Las Playas', comuna: '16 - Belén' },
  { barrio: 'Diego Echavarría', comuna: '16 - Belén' },
  { barrio: 'La Mota', comuna: '16 - Belén' },
  { barrio: 'La Hondonada', comuna: '16 - Belén' },
  { barrio: 'El Rincón', comuna: '16 - Belén' },
  { barrio: 'La Loma de Los Bernal', comuna: '16 - Belén' },
  { barrio: 'La Gloria', comuna: '16 - Belén' },
  { barrio: 'Altavista', comuna: '16 - Belén' },
  { barrio: 'La Palma', comuna: '16 - Belén' },
  { barrio: 'Los Alpes', comuna: '16 - Belén' },
  { barrio: 'Las Violetas', comuna: '16 - Belén' },
  { barrio: 'Las Mercedes', comuna: '16 - Belén' },
  { barrio: 'Nueva Villa de Aburrá', comuna: '16 - Belén' },
  { barrio: 'Miravalle', comuna: '16 - Belén' },
  { barrio: 'El Nogal – Los Almendros', comuna: '16 - Belén' },
  { barrio: 'Cerro Nutibara', comuna: '16 - Belén' },
]
